export enum LogEvent {
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTER = 'USER_REGISTER',
  CATEGORY_CREATE = 'CATEGORY_CREATE',
  CATEGORY_DELETE = 'CATEGORY_DELETE',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE'
}